### PR TITLE
Embed Base64-Encoded Images Inline

### LINKED ISSUE #88: Embed Base64-Encoded Images Inline In HTML?
**Is your feature request related to a problem? Please describe.**

Currently, an image/figure is exported as just `<figure title="bbox X X X X"/>`

**Describe the solution you'd like**

Embed an image/figure inline. `;base64,<BASE64_ENCODED_IMAGE>”>`

**Describe alternatives you've considered**

Save an image/figure as a separate file and add the image location like ``.

**Additional context**

### PR DESCRIPTION
**Pull request by HiromuHota**
## Description of the problems or issues

**Is your pull request related to a problem? Please describe.**

See #88

**Does your pull request fix any issue.**

Close #88

## Description of the proposed changes

Embed base64-encoded images inline. Support starting with JPEG and BMP.

## Test plan

Apply pdftotree to pdfs and see if JPEG and BMP images are extracted.

## Checklist

* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] I have updated the CHANGELOG.md accordingly.

### CODE REVIEW

**Comment by lukehsiao** [comment]
What happens today for a PNG?

**Comment by lukehsiao** [comment]
Ah, I see now that it looks like you can just specify the MIME type, so we should be able to support a wide variety of image formats this way, right?

**Review by lukehsiao — APPROVED** [review]
Seems reasonable to me.

**Comment by HiromuHota** [comment]
> Ah, I see now that it looks like you can just specify the MIME type, so we should be able to support a wide variety of image formats this way, right? Basically, I want to check that this approach will be support a wide variety of images.

Yes, this approach can support a wide variety of image types. PNG is another supported type.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
In fact, JPEG and BMP are just an initial set of supported types. We will add PNG and other types too when we have such an example PDF containing different types of image.

I like the fact that hOCR with embedded images is more portable than hOCR with multiple images.
Please let me know your thoughts and experiences.

**Comment by lukehsiao** [comment]
> I like the fact that hOCR with embedded images is more portable than hOCR with multiple images.
> Please let me know your thoughts and experiences.

I don't know about portable vs not portable, but I think embedding them seems just fine. I assume I could download the embedded image as a file anyways, right?

**Comment by HiromuHota** [comment]
@lukehsiao Yes, you can open an exported hocr and save an embedded image as a separate file.
In the future, pdftotree might have options like `--embed-image <0|1> (Default: 1)` as in pdf2htmlEX.
https://github.com/coolwanglu/pdf2htmlEX/wiki/Command-Line-Options
With this, you can control whether images are embedded or saved as a separate file.

**Comment by lukehsiao** [comment]
Sounds great. Feel free to merge whenever you'd like.

**Comment by HiromuHota** [comment]
For future reference, this PR relies on pdfminer.six for image type detection, which cannot detect an image type sometimes.
This PR embeds images only when their image types are detected and does not embed the image of unknown type.
To detect an image type on broader cases, we have to
- Enhance and contribute to pdfminer.six, or
- Use a different library or implement it on our own.

**Pull request merged**
